---

- name: Add the OS specific varibles
  include_vars: Debian.yml

- name: Install the required packages in Debian derivatives
  apt: name={{ item }} state=installed update_cache=yes
  with_items: ntp_pkgs

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
   - restart ntp


