if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

source /usr/local/share/chruby/chruby.sh

export JRUBY_HOME=/opt/jruby
export GEM_HOME=/opt/jruby/gems
export GEM_PATH=/opt/jruby/gems

pathmunge () {
if ! echo $PATH | /usr/bin/egrep -q "(^|:)$1($|:)" ; then
   if [ "$2" = "after" ] ; then
      PATH=$PATH:$1
   else
      PATH=$1:$PATH
   fi
fi
}

if [ -d "$JRUBY_HOME/bin" ] ; then
  pathmunge $JRUBY_HOME/bin after
fi

if [ -d "$GEM_HOME/bin" ] ; then
  pathmunge $GEM_HOME/bin after
fi

export PATH

